[project]
name = "agent-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "stone", email = "2398391057@qq.com" }
]
requires-python = ">=3.14"
dependencies = [
    "agentscope<2",
    "camel-ai>=0.2.90",
    "json5>=0.15.0",
    "mcp[cli]<2",
    "openai>=3.1.0",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
agent-project = "agent_project:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "agent_project"
